env:
  global:
  - CIBW_BEFORE_BUILD="yum install -y gcc glibc.i686 && pip install numpy cython &&
    cd docker && bash cmake.bash && bash assimp.bash"
  - CIBW_TEST_REQUIRES="pytest"
  - CIBW_TEST_COMMAND="pytest {project}/tests"
matrix:
  include:
  - dist: trusty
    sudo: required
    language: python
    python: '3.6'
    services:
    - docker
install:
- if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then brew install python3; fi
- pip3 install cibuildwheel==0.10.1
script:
- cibuildwheel --output-dir wheelhouse
- python -m pip install twine
- python -m twine upload wheelhouse/*.whl
