env:
  global:
  - CIBW_BEFORE_BUILD="yum install -y gcc glibc.i686 && pip install numpy cython &&
    cd docker && bash cmake.bash && bash assimp.bash"
  - CIBW_TEST_REQUIRES="pytest"
  - CIBW_TEST_COMMAND="pytest {project}/tests"
  - secure: bKxjnMrbhB7qd8aKd77hr1PMWSwoEXqWPm7tW2zoaX2OJnelULSBVk69qp2js8cuT1lQmfDHO6TqmjaLbM8UTM+OPYNzDUgDJKUbuJ3uAWDFOTgO7Vsk5ZcxjdQvH+TsvP5LO4Zcuab05hR/CplmVP7APPpRzEZsOo151jrQ1X5dw6GFwkOOCWyrbgwcO7SYQ2E/g41oQmR4RU2c471d778OJa2Bq5l6WR3pDiO+in6h4xJFJsTfpN64b6mWslaLuYMo7bWijeVlS0yRX3yDJJ3NEDoB3Dor01bojjN08mdWh/yuFbhMzfqqvc4E12nGxkpAgkqBIeNYUh4jnbQhUaRHgGTlNJRqq5KazCq83Gc83XpVpMk8LOCDkCkLbYoXDm5p3iFRBcmE9wRBzFt7MQ26YNagoQZnIYsG4NgMS0y1Bla7eIOib13n87lJg6qsbUv/s+tZQdLFbaQjM29fkg4QEltbqF/10u0+aPcfRdG6PuA2fQf8PH2OaPUIA14nb+2h+yV2YVGdeq0cv+yQYeX63WQoTLPfMG7WW8XseRLjf+CSKcTziNRfy9+uNzk824bgHj73AzJN3D7gGpXYn0AduW983snExK4nc4h30hzqAWIY/jOXxduwfaxnHBfetRxBuHsaM47g7rl4WlUOAgh+KIhqZVLQ7py6nF01vcs=
  - secure: aO9WSkEtxljSirWS/2sP691QWYFukaQkTZHOhFX9l3o7Wr/t4Jgo4AhJLS+lwtkPu1ChQ1JP5XR77S2GU2RZuw7BT4BzJUHUOynJDZgOx/ja+nHNjHRlVyEHnsCUzTk04UiBfIAEGlOM//XEVTpHam8j0tIyhEqcbNeromcptZ+2Lj9ZGxqY9PE02Ik5vRaeno6daAk89l1vURN4e2M76bKuu8zGXKaH3rKkUwC3vJBjVV0X5X+45zlwAy/Ddww12uMqdfTB1ltRnGSvxZfxltdnzKv2bnHHFlRRoOVhy3NCTyjrHOxjh3/E8X4ZWMbU1mv0QqY32grTvYh8idH6+x+yBMF7SwmXoTZUuvwO5K5sI34XiPm0t/AF7U/5UcEzYpBSEL0AyKsOryLKNL4DToUVM0arX7dibNrw//yZc8lk+riDQMC97kZfNAj12hC+pBDxWND4voEHGISfwfitx44emHx+gbb77hC+bqwLK0yWrZX6e47qCGJXomkqZ5Qwu5pVRrooKf0DdzcZnFNvcKlTgS41zrQy8dDzqenL405TJNFlPTG/54kRPcdBLPwfaNUuHcj/x52olJ6wcK/dhbMXGvx0yhFWswJ5HxcDaLelX4+w3BHN9CRD6c4yrrMzlKNTZt3RgwCrg76yW2MEEECpfIEzkiOqKjmSuBNxl3o=
matrix:
  include:
  - dist: trusty
    sudo: required
    language: python
    python: '3.6'
    services:
    - docker
install:
- if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then brew install python3; fi
- pip3 install cibuildwheel==0.10.1
script:
- cibuildwheel --output-dir wheelhouse
- python -m pip install twine
- python -m twine upload wheelhouse/*.whl
